### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by johnmccabe** [muldjord/leddy#1]
Hi Lars,
Absolutely brilliant to see what you've done with the model I uploaded, I love this !!!

Out of interest, what did you end up using as a diffuser. I've never been happy with the paper I used, haven't explored alternatives yet though.

Also, I'd be very interested to see what you did to improve the corner support.

All the best,
John

**Comment by muldjord** [comment]
Hi John,
Great to hear from you! Thank you for uploading the frame design and 3D print models. I have iterated quite a bit on the diffuser since I also wasn't quite satisfied with using a piece of paper. My current iteration is 95% perfect to what I wanted to accomplish.

I ended up buying some semi-transparent PLA and printed a full "tiny-square with small pyramids on top"  (16x16 of these) matrix that fit into the frame you uploaded. Each square is about 3 mm high and they are printed on a very thin piece of PLA to keep them in line. I'll upload pictures and the model.

**Comment by muldjord** [comment]
[leddy_diffuser_model.zip](https://github.com/muldjord/leddy/files/6178521/leddy_diffuser_model.zip)

**Comment by muldjord** [comment]
These are images of the diffuser. Pay no mind to the red frame. That is my test frame. The frames I have mounted are black. I'll upload the corner pieces too. I just need to find the models.

![DSC_0778](https://user-images.githubusercontent.com/4451640/111923277-a6a18080-8a9e-11eb-9007-ca557c00519e.JPG)
![DSC_0779](https://user-images.githubusercontent.com/4451640/111923279-a99c7100-8a9e-11eb-9a19-3e9a0fa9a4b1.JPG)
![DSC_0780](https://user-images.githubusercontent.com/4451640/111923281-ab663480-8a9e-11eb-9eb9-dfcb2334149a.JPG)

**Comment by muldjord** [comment]
I've recorded a quick and dirty disassembly video that shows the corner pieces and the change I've made to them: https://youtu.be/pCzFyc1Hh1c

Let me know if you'd rather not have your name mentioned. I will re-record it without if you prefer.

**Comment by johnmccabe** [comment]
Oh, I hadn't considered printing the diffuser, good call. No worries on mentioning names.

Thanks a lot for sharing, I'll have to grab some of the semi-transparent PLA and update my frame 👍

**Comment by muldjord** [comment]
I'd love to see your result if you do, so feel free to let me know.

**Comment by johnmccabe** [comment]
Will do !
